### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by Feno4ka** [esthvan/call_of_flesh#56]
Когда пытаюсь скомпилировать, вылезает ошибка
`fenicu@fenicu:/opt/call_of_flesh$ sudo DreamMaker ss13_stalker.dme`
`DM compiler version 512.1448`
`loading ss13_stalker.dme`
`loading interface/skin.dmf`
`code/game/stalker/anomalies/anomaly.dm:415:error: circleturfs: undefined proc`
`ss13_stalker.dmb - 1 error, 0 warnings (9/25/18 2:04 am)`

**Comment by Feno4ka** [comment]
На винде тоже самое, хз зачем проверял

**Comment by esthvan** [comment]
Fixed.
Обновись до последней версии
